apiVersion: v1
kind: Pod
metadata:
  name: nodehelloworld
  labels:
    app: helloworld
spec:
  containers:
  - name: kube-demo
    image: rkarigela/nodehelloworld
    ports:
    - name: nodejs-port
      containerPort: 3000
